import React from "react";
import { Select, Button } from "@rtdui/core";

const fruits = [
	"Alfalfa Sprouts xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"Apple",
	"Apricot",
	"Artichoke",
	"Asian Pear",
	"Asparagus",
	"Atemoya",
	"Avocado",
	"Bamboo Shoots",
	"Banana",
	"Bean Sprouts",
	"Beans",
	"Beets",
	"Belgian Endive",
	"Bell Peppers",
	"Bitter Melon",
	"Blackberries",
	"Blueberries",
	"Bok Choy",
	"Boniato",
	"Boysenberries",
	"Broccoflower",
	"Broccoli",
	"Brussels Sprouts",
	"Cabbage",
	"Cactus Pear",
	"Cantaloupe",
	"Carambola",
	"Carrots",
	"Casaba Melon",
	"Cauliflower",
	"Celery",
	"Chayote",
	"Cherimoya",
	"Cherries",
	"Coconuts",
	"Collard Greens",
	"Corn",
	"Cranberries",
	"Cucumber",
	"Dates",
	"Dried Plums",
	"Eggplant",
	"Endive",
	"Escarole",
	"Feijoa",
	"Fennel",
	"Figs",
	"Garlic",
	"Gooseberries",
	"Grapefruit",
	"Grapes",
	"Green Beans",
	"Green Onions",
	"Greens",
	"Guava",
	"Hominy",
	"Honeydew Melon",
	"Horned Melon",
	"Iceberg Lettuce",
	"Jerusalem Artichoke",
	"Jicama",
	"Kale",
	"Kiwifruit",
	"Kohlrabi",
	"Kumquat",
	"Leeks",
	"Lemons",
	"Lettuce",
	"Lima Beans",
	"Limes",
	"Longan",
	"Loquat",
	"Lychee",
	"Madarins",
	"Malanga",
	"Mandarin Oranges",
	"Mangos",
	"Mulberries",
	"Mushrooms",
	"Napa",
	"Nectarines",
	"Okra",
	"Onion",
	"Oranges",
	"Papayas",
	"Parsnip",
	"Passion Fruit",
	"Peaches",
	"Pears",
	"Peas",
	"Peppers",
	"Persimmons",
	"Pineapple",
	"Plantains",
	"Plums",
	"Pomegranate",
	"Potatoes",
	"Prickly Pear",
	"Prunes",
	"Pummelo",
	"Pumpkin",
	"Quince",
	"Radicchio",
	"Radishes",
	"Raisins",
	"Raspberries",
	"Red Cabbage",
	"Rhubarb",
	"Romaine Lettuce",
	"Rutabaga",
	"Shallots",
	"Snow Peas",
	"Spinach",
	"Sprouts",
	"Squash",
	"Strawberries",
	"String Beans",
	"Sweet Potato",
	"Tangelo",
	"Tangerines",
	"Tomatillo",
	"Tomato",
	"Turnip",
	"Ugli Fruit",
	"Water Chestnuts",
	"Watercress",
	"Watermelon",
	"Waxed Beans",
	"Yams",
	"Yellow Squash",
	"Yuca/Cassava",
	"Zucchini Squash",
];

export default function Demo() {
	const [submitData, setSubmitData] = React.useState<FormData | null>(null);
	const handleFormSubmit = (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		const formData = new FormData(e.target as HTMLFormElement);
		setSubmitData(formData);
	};
	let output = "";
	if (submitData) {
		for (const [key, value] of submitData) {
			output += `${key}: ${value}\n`;
		}
	}
	return (
		<form onSubmit={handleFormSubmit} className="flex flex-col gap-4">
			<Select name="mySelect" color="primary" data={fruits} />
			<Button type="submit">提交</Button>
			<output className="bg-base-100 mt-4 p-4">
				提交的数据:
				<pre>{output}</pre>
			</output>
		</form>
	);
}
Demo.displayName = "SelectInFormDemo";
